---
# Deployment of our synthetic-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: synthetic-service
  namespace: keptn
spec:
  selector:
    matchLabels:
      run: synthetic-service
  replicas: 1
  template:
    metadata:
      labels:
        run: synthetic-service
    spec:
      containers:
        - name: synthetic-service
          image: checkelmann/synthetic-service:latest # Todo: Replace this with your image name
          ports:
            - containerPort: 8080
          env:
            - name: EVENTBROKER
              value: 'http://event-broker.keptn.svc.cluster.local/keptn'
            - name: CONFIGURATION_SERVICE
              value: 'http://configuration-service.keptn.svc.cluster.local:8080'
---
# Expose synthetic-service via Port 8080 within the cluster
apiVersion: v1
kind: Service
metadata:
  name: synthetic-service
  namespace: keptn
  labels:
    run: synthetic-service
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    run: synthetic-service
---
## Subscribe to events via a keptn/distributor
apiVersion: apps/v1
kind: Deployment
metadata:
  name: synthetic-service-distributor
  namespace: keptn
spec:
  selector:
    matchLabels:
      run: distributor
  replicas: 1
  template:
    metadata:
      labels:
        run: distributor
    spec:
      containers:
        - name: distributor
          image: keptn/distributor:0.6.1
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: PUBSUB_URL
              value: 'nats://keptn-nats-cluster'
            # listen to all events in sh.keptn. - see https://github.com/keptn/spec/blob/0.1.3/cloudevents.md
            - name: PUBSUB_TOPIC
              value: 'sh.keptn.>'
            - name: PUBSUB_RECIPIENT
              value: 'synthetic-service'
